basePath: /v1
host: localhost:8080
info:
  contact:
    email: team@sonr.io
    name: Sonr Inc.
    url: https://sonr.io
  description: Manage your Sonr Powered services and blockchain registered types with
    the Highway API.
  license:
    name: OpenGLv3
  title: Highway API
  version: v0.23.0
paths:
  /Object/update:
    post:
      description: UpdateObject updates and object reference for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Object
  /blob/download/:cid:
    get:
      description: DownloadBlob downloads a file from storage given its CID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Download File
  /blob/remove/:cid:
    get:
      description: RemoveBlob deletes a file from storage given its CID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Remove Blob
  /blob/upload:
    post:
      description: UploadBlob uploads a file to storage and returns its CID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload File
  /bucket/deactivate/:cid:
    get:
      description: DeactivateBucket disables a bucket for a registered application
        via HTTP.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "502":
          description: Bad Gateway
          schema:
            type: string
      summary: Deactivate Bucket
  /channel/create:
    post:
      description: CreateChannel creates a specified channel for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Channel
  /channel/deactivate:
    post:
      description: DeactivateChannel disables a Channel for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Deactivate Channel
  /channel/deactivate/:cid:
    post:
      description: DeactivateObject disables a Object for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Deactivate Object
  /channel/listen:
    post:
      description: ListenChannel puts a Channel into a listening state registered
        application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Listen Channel
  /channel/update:
    post:
      description: ListenChannel puts a Channel into a listening state registered
        application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Channel
  /name/update:
    post:
      description: DeactivateChannel disables a Channel for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Name
swagger: "2.0"
