basePath: /v1
host: localhost:8080
info:
  contact:
    email: team@sonr.io
    name: Sonr Inc.
    url: https://sonr.io
  description: Manage your Sonr Powered services and blockchain registered types with
    the Highway API.
  license:
    name: OpenGLv3
  title: Highway API
  version: v0.23.0
paths:
  /blob/download/:cid:
    get:
      description: DownloadBlob downloads a buffer or file from IPFS given its CID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Download File
      tags:
      - Blob
  /blob/remove/:cid:
    post:
      description: RemoveBlob deletes a buffer or file from IPFS given its CID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Remove Blob
      tags:
      - Blob
  /blob/upload:
    post:
      description: UploadBlob uploads a buffer or file to IPFS and returns its CID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload Blob
      tags:
      - Blob
  /bucket/create:
    post:
      description: CreateBucket creates a new bucket instance for a registered application on the blockchain.
        via HTTP.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Bucket
      tags:
      - Bucket
  /bucket/deactivate:
    post:
      description: DeactivateBucket disables a bucket for a registered application on the blockchain.
        via HTTP.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "502":
          description: Bad Gateway
          schema:
            type: string
      summary: Deactivate Bucket
      tags:
      - Bucket
  /bucket/update:
    post:
      description: UpdateBucket updates a bucket for a registered application via
        HTTP.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Bucket
      tags:
      - Bucket
  /channel/create:
    post:
      description: CreateChannel creates a specified channel for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Channel
      tags:
      - Channel
  /channel/deactivate:
    post:
      description: DeactivateChannel disables a Channel for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Deactivate Channel
      tags:
      - Channel
  /channel/listen:
    post:
      description: ListenChannel puts a Channel into a listening state registered
        application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Listen Channel
      tags:
      - Channel
  /channel/update:
    post:
      description: ListenChannel puts a Channel into a listening state registered
        application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Channel
      tags:
      - Channel
  /name/access/finish/:username:
    post:
      description: FinishAccessName finishes the authentication process and returns
        a PublicKeyCredentialResponse. Succesfully logging in a Sonr Account.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Finish Access Name
      tags:
      - Registry
  /name/access/start/:username:
    get:
      description: StartAccessName accesses the user's existing credentials and returns
        a PublicKeyCredentialRequestOptions. Beggining the authentication process.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Start Access Name
      tags:
      - Registry
  /name/register/finish/:username:
    post:
      description: FinishRegisterName finishes the registration process and returns
        a PublicKeyCredentialResponse. Succesfully registering a WebAuthn credential
        to a Sonr Account.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Finish Register Name
      tags:
      - Registry
  /name/register/start/:username:
    get:
      description: StartRegisterName starts the registration process and returns a
        PublicKeyCredentialCreationOptions. Initiating the registration process for
        a Sonr Account.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Start Register Name
      tags:
      - Registry
  /name/update:
    post:
      description: UpdateName updates a name on the Sonr blockchain registry.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Name
      tags:
      - Registry
  /object/create:
    post:
      description: CreateObject creates a Object for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Object
      tags:
      - Object
  /object/deactivate:
    post:
      description: DeactivateObject disables a Object for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Deactivate Object
      tags:
      - Object
  /object/update:
    post:
      description: UpdateObject updates and object reference for a registered application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update Object
      tags:
      - Object
swagger: "2.0"
