version: "3"

vars:
  VERSION: v0.0.1-test

includes:
  motor:
    taskfile: ./bind/Taskfile.yaml
    dir: ./bind
  # motorkit:
  #   taskfile: ../Motorkit/Taskfile.yaml
  #   dir: ../MotorKit

tasks:
  ## ------------------------------------------------------------
  ## Node tasks
  ## ------------------------------------------------------------
  motorkit:
    summary: Binding motor to iOS and updating motorkit
    cmds:
      - task: clean
      - task: motor:bind:ios
      - mv ./bind/build ./build

  chain:build:
    summary: "Build cosmos blockchain using ignite"
    cmds:
      - ignite chain build

  chain:serve:
    summary: Serve the blockchain using ignite
    cmds:
      - ignite chain serve
    silent: true

  highway:serve:
    summary: Serve the highway daemon using ignite
    cmds:
      - go run cmd/highwayd/main.go
    silent: true

  ## ------------------------------------------------------------
  ## Documentation tasks
  ## ------------------------------------------------------------
  docs:start:
    summary: "Calls yarn start in docs directory"
    cmds:
      - task: swag:build
      - yarn start
    silent: true
    dir: docs

  docs:build:
    summary: "Calls yarn build in docs directory"
    cmds:
      - task: swag:build
      - yarn build
    silent: true
    dir: docs

  docs:swizzle:
    summary: "Calls yarn swizzle in docs directory"
    cmds:
      - yarn swizzle
    silent: true
    dir: docs

  docs:deploy:
    summary: "Calls yarn deploy in docs directory"
    cmds:
      - USE_SSH=true yarn deploy
    silent: true
    dir: docs

  docs:clear:
    summary: "Calls yarn clear in docs directory"
    cmds:
      - yarn clear
    silent: true
    dir: docs

  docs:serve:
    summary: "Calls yarn serve in docs directory"
    cmds:
      - yarn serve
    silent: true
    dir: docs

  ## ------------------------------------------------------------
  ## Protobuf tasks
  ## ------------------------------------------------------------
  buf:
    summary: "Build and Push Protobuf files to buf.build"
    dir: pkg/motor/proto
    cmds:
      - buf mod update
      - buf build
      - buf push {{.CLI_ARGS}}
      - task: clean

  proto:go:
    summary: "Generate cosmos-sdk protobuf files using ignite"
    cmds:
      - ignite generate proto-go
      - go mod tidy

  swag:build:
    summary: "Generate swagger files for highway and blockchain using ignite"
    cmds:
      - swag i -d ./ -g pkg/highway/api/server.go -o docs/static
      - mv docs/static/swagger.yaml docs/static/highway.yaml
      - rm -rf docs/static/swagger.json

  wallet:dev:
    summary: "Run wallet in development mode"
    dir: web/wallet
    cmds:
      - npm run dev

  ## ------------------------------------------------------------
  ## Utility tasks
  ## ------------------------------------------------------------
  default:
    summary: "Displays tasks and descriptions"
    cmds:
      - task --list-all

  release:
    summary: "Create a local release for all binaries using goreleaser"
    cmds:
      - goreleaser release --skip-publish --snapshot --rm-dist --parallelism 4

  clean:
    summary: "Clean all binaries and generated files and directories"
    cmds:
      - task: motor:clean
      - rm -rf ./build
      - rm -rf ./dist
      - rm -rf ./io.sonr.motor.aar
      - rm -rf ./sonr-motor.wasm
      - rm -rf ./SonrMotor.xcframework
      - rm -rf ./docs/.docusaurus/
      - rm -rf ./docs/build
      - go mod tidy
      - go get -u go.buf.build/grpc/go/sonr-io/motor
