version: "3"

vars:
  VERSION: v0.0.1-test

tasks:
  ## ------------------------------------------------------------
  ## Node tasks
  ## ------------------------------------------------------------
  bind:
    cmds:
      - task: clean
      #- task: bind:wasm
      - task: bind:ios
      - task: bind:android

  bind:android:
    dir: motor-mobile
    cmds:
      - gomobile bind -ldflags='-s -w' -target=android/arm64 -o io.sonr.motor.aar -v
      - rm -rf io.sonr.motor-sources.jar
      - mv io.sonr.motor.aar ../build/io.sonr.motor.aar

  bind:ios:
    dir: motor-mobile
    cmds:
      - gomobile bind -ldflags='-s -w' -target=ios -prefix=SNR -o Motor.xcframework -v
      - mv Motor.xcframework ../build/Motor.xcframework

  bind:wasm:
    dir: motor-wasm
    cmds:
      - mkdir motorlib-wasm
      - GOOS=js GOARCH=wasm go build -tags wasm -o motorlib-wasm/motor.wasm -v
      - mv motor.wasm ../build/motor.wasm

  clean:
    cmds:
      - find ./ -type d -name "Motor.xcframework" -exec rm -rf {} +
      - find ./ -type d -name "motor.wasm" -exec rm -rf {} +
      - find ./ -type d -name "io.sonr.motor.aar" -exec rm -rf {} +
      - find ./ -type d -name "build" -exec rm -rf {} +
      - mkdir -p build
